### ISSUE TITLE
varint

### ISSUE THREAD

**Issue by NacJidtyd6op** [ph4r05/monero-serialize#1]
i cant understand how to convert varint to decimal  and the opposite

for example 

monero-serialize.encode(number)

monero-serialize.decode(number)

**Comment by ph4r05** [comment]
Depends on which uvarint (Blockchain / RPC / Boost).

Blockchain:

```python
from monero_serialize.core.int_serialize import dump_uvarint_b, load_uvarint_b
dump_uvarint_b(42)
```
